name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Generate .env files
        run: |
          echo "Generating .env files..."

          # Create .env for api-gateway
          mkdir -p api-gateway
          echo "PORT=${{ secrets.API_GATEWAY_PORT }}" > api-gateway/.env
          echo "NODE_ENV=production" >> api-gateway/.env
          echo "IDENTITY_SERVICE_URL=${{ secrets.API_GATEWAY_IDENTITY_SERVICE_URL }}" >> api-gateway/.env
          echo "POST_SERVICE_URL=${{ secrets.API_GATEWAY_POST_SERVICE_URL }}" >> api-gateway/.env
          echo "MEDIA_SERVICE_URL=${{ secrets.API_GATEWAY_MEDIA_SERVICE_URL }}" >> api-gateway/.env
          echo "SEARCH_SERVICE_URL=${{ secrets.API_GATEWAY_SEARCH_SERVICE_URL }}" >> api-gateway/.env
          echo "JWT_SECRET=${{ secrets.API_GATEWAY_JWT_SECRET }}" >> api-gateway/.env
          echo "RABBITMQ_URL=${{ secrets.API_GATEWAY_RABBITMQ_URL }}" >> api-gateway/.env
          echo "REDIS_URL=${{ secrets.API_GATEWAY_REDIS_URL }}" >> api-gateway/.env

          # Create .env for identity-service
          mkdir -p identity-service
          echo "PORT=${{ secrets.IDENTITY_SERVICE_PORT }}" > identity-service/.env
          echo "MONGODB_URI=${{ secrets.IDENTITY_SERVICE_MONGODB_URI }}" >> identity-service/.env
          echo "JWT_SECRET=${{ secrets.IDENTITY_SERVICE_JWT_SECRET }}" >> identity-service/.env
          echo "NODE_ENV=production" >> identity-service/.env
          echo "REDIS_URL=${{ secrets.IDENTITY_SERVICE_REDIS_URL }}" >> identity-service/.env
          echo "RABBITMQ_URL=${{ secrets.IDENTITY_SERVICE_RABBITMQ_URL }}" >> identity-service/.env

          # Add similar sections for other services as needed...

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add VPS SSH host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 46.202.195.200 >> ~/.ssh/known_hosts

      - name: Set up SSH key for authentication
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 46.202.195.200
          username: root
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/harrytimbog/social-media-microservices/NodeHive
            git pull origin master

            # Ensure environment files are in place on VPS
            echo "Uploading .env files to VPS..."

            # Manually create .env files or transfer them from GitHub runner to VPS

            # Stop existing containers
            docker-compose down

            # Start containers with the updated configuration
            docker-compose up -d

      - name: Debug SSH connection (optional)
        run: |
          ssh -v -i ~/.ssh/id_rsa root@46.202.195.200 "echo 'SSH connection successful'"
        continue-on-error: true
